# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x08location\"A\n\x12\x46indNearestRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\x12\x11\n\tradius_km\x18\x03 \x01(\x02\"5\n\x0e\x44riverResponse\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x32Y\n\nGeoService\x12K\n\x11\x46indNearestDriver\x12\x1c.location.FindNearestRequest\x1a\x18.location.DriverResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINDNEARESTREQUEST']._serialized_start=28
  _globals['_FINDNEARESTREQUEST']._serialized_end=93
  _globals['_DRIVERRESPONSE']._serialized_start=95
  _globals['_DRIVERRESPONSE']._serialized_end=148
  _globals['_GEOSERVICE']._serialized_start=150
  _globals['_GEOSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
